#!/usr/bin/env bash

# JankyBorders configuration for AeroSpace.
# Colors use the 0xAARRGGBB format expected by `borders`.
options=(
  style=round
  width=5.0
  hidpi=off
  active_color=0xff7aa2f7
  inactive_color=0xff414868
)

borders "${options[@]}"